openapi: 3.0.1
info:
  title: API - Rueiros do Bem
  description: API backend para o Projeto Rueiros do Bem
  termsOfService: http://TBD
  contact:
    email: TBD@tbd.com
  license:
    name: Licença não definida
    url: http://TBD
  version: 1.0.0
externalDocs:
  description: 'Repositório do Projeto'
  url: 'https://github.com/TemAula/rdb-backend-quarkus'
servers:
  - url: /
  # Caso o modo dev do quarkus estiver executando e ouvindo na porta 8080
  - url: http://localhost:8080/
tags:
  - name: eventos
    description: 'Endpoints relacionados aos Eventos'

  - name: itens
    description: Endpoints relacionados aos Itens
paths:
  /eventos/{id}:
    put:
      tags:
        - eventos
      description: Atualiza um evento registrado
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AtualizarEventoRequest'
        required: true
      responses:
        200:
          description: Retorna o evento atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AtualizarEventoResponse'
        400:
          description: Requisição inválida
          content: {}
        404:
          description: Evento não encontrado
          content: {}


components:
  schemas:

    Periodo:
      type: object
      properties:
        dataInicio:
          type: string
          format: date
        dataFim:
          type: string
          format: date
      required:
        - dataInicio
        - dataFim

    AtualizarEventoRequest:
      type: object
      properties:
        nome:
          type: string
        descricao:
          type: string
        periodoVigencia:
          $ref: '#/components/schemas/Periodo'
      required:
        - nome
        - periodoVigencia

    AtualizarEventoResponse:
      type: object
      properties:
        id:
          type: number
        nome:
          type: string
        descricao:
          type: string
        periodoVigencia:
          $ref: '#/components/schemas/Periodo'
  