openapi: 3.0.1
info:
  title: API - Rueiros do Bem
  description: API backend para o Projeto Rueiros do Bem
  termsOfService: http://TBD
  contact:
    email: TBD@tbd.com
  license:
    name: Licença não definida
    url: http://TBD
  version: 1.0.0
externalDocs:
  description: 'Repositório do Projeto'
  url: 'https://github.com/TemAula/rdb-backend-quarkus'
servers:
- url: /
# Caso o modo dev do quarkus estiver executando e ouvindo na porta 8080
- url: http://localhost:8080/
tags:
- name: eventos
  description: 'Endpoints relacionados aos Eventos'
  
- name: itens
  description: Endpoints relacionados aos Itens
paths:
  /itens/{id}:
    delete:
      tags:
      - itens
      description: Remove um item registrado
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        202:
          description: Informa que removeu o item informado
          content: {}
        400:
          description: id do item está inválido
          content: {}
        404:
          description: Item não encontrado
          content: {}
               