swagger: "2.0"
info:
  description: "API backend para o Projeto Rueiros do Bem"
  version: "1.0.0"
  title: "API - Rueiros do Bem"
  termsOfService: "http://TBD"
  contact:
    email: "TBD@tbd.com"
  license:
    name: "TBD Licence"
    url: "http://TBD"
# basePath: "/"
tags:
- name: "eventos"
  description: "Endpoints relacionados aos Eventos"
  externalDocs:
    description: "TBD - External docs"
    url: "http://TBD"
- name: "itens"
  description: "Endpoints relacionados aos Itens"

consumes:
- "application/json"
produces:
- "application/json"

responses:
  '400':
    description: "Erros de validação"
    schema:
      $ref: "#/definitions/MensagensResponse"
  '500':
    description: "Erros internos do servidor"
    schema:
      $ref: "#/definitions/MensagensResponse"
paths:
  
  '/eventos':
    get:
      description: 'Lista todos os eventos registrados' 
      tags:
      - 'eventos'
      responses:
        '200':
          description: 'Lista de todos os eventos registrados'
          schema:
            $ref: "#/definitions/ListaDeEventos"
    post:
      description: 'Adiciona um novo evento'
      tags:
      - 'eventos'
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/NovoEventoRequest"
      responses:
        '200':
          description: "novo evento registrado"
          schema:
            $ref: "#/definitions/NovoEventoResponse"
   
  '/eventos/{id}':
    get:
      description: 'Retorna o evento para o id informado' 
      tags:
      - 'eventos'
      parameters:
      - in: 'path'
        name: 'id'
        type: 'number'
        required: true
      responses:
        '200':
          description: 'Retorna o evento registrados para o id informado'
          schema:
            $ref: "#/definitions/EventoRegistrado"
    
    put:
      description: 'Atualiza um evento registrado' 
      tags:
      - 'eventos'
      parameters:
      - in: 'path'
        name: 'id'
        type: 'number'
        required: true
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/AtualizarEventoRequest"
      responses:
        '200':
          description: 'Retorna o evento atualizado'
          schema:
            $ref: "#/definitions/AtualizarEventoResponse"
    
    delete:
      description: 'Remove um evento registrado' 
      tags:
      - 'eventos'
      parameters:
      - in: 'path'
        name: 'id'
        type: 'number'
        required: true
      responses:
        '204':
          description: 'Informa que removeu o eventos informado'
          
  '/eventos/{eventoId}/itens':
    get:
      description: 'Retorna os itens relacionados ao evento para o id informado' 
      tags:
      - 'eventos'
      parameters:
      - in: 'path'
        name: 'eventoId'
        description: 'Id do evento'
        type: 'number'
        required: true
      responses:
        '200':
          description: 'Lista de todos os itens relacionados para o evento informado'
          schema:
            $ref: "#/definitions/ListaItemEvento"
    post:
      description: 'Registrar um item ao evento para o id informado' 
      tags:
      - 'eventos'
      parameters:
      - in: 'path'
        name: 'eventoId'
        description: 'Id do evento'
        type: 'number'
        required: true
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/RegistrarItemEventoRequest"
      responses:
        '200':
          description: 'Lista de todos os itens relacionados para o evento informado'
          schema:
            $ref: "#/definitions/RegistrarItemEventoResponse"
            
  '/eventos/{eventoId}/itens/{itemId}':  
  
    delete:
      description: 'Remove um item do evento para o id informado' 
      tags:
      - 'eventos'
      parameters:
      - in: 'path'
        name: 'eventoId'
        description: 'Id do Evento'
        type: 'number'
        required: true
      - in: 'path'
        name: 'itemId'
        description: 'Id do item do evento registrado'
        type: 'number'
        required: true
      responses:
        '204':
          description: 'Informa que removeu o item do evendo informado'
          
  '/itens':
    post:
      description: 'Adiciona um novo item'
      tags:
      - 'itens'
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/NovoItemRequest"
      responses:
        '200':
          description: "novo item registrado"
          schema:
            $ref: "#/definitions/NovoItemResponse"
            
    get:
      description: 'Lista todos os itens registrados' 
      tags:
      - 'itens'
      responses:
        '200':
          description: 'Lista de todos os itens registrados'
          schema:
            $ref: "#/definitions/ListaDeItens"
  
  '/itens/{id}':
    get:
      description: 'Retorna o item para o id informado' 
      tags:
      - 'eventos'
      parameters:
      - in: 'path'
        name: 'id'
        type: 'number'
        required: true
      responses:
        '200':
          description: 'Retorna o iten registrado para o id informado'
          schema:
            $ref: "#/definitions/ItemRegistrado"
    
    put:
      description: 'Atualiza item registrado' 
      tags:
      - 'itens'
      parameters:
      - in: 'path'
        name: 'id'
        type: 'number'
        required: true
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/AtualizarItemRequest"
      responses:
        '200':
          description: 'Retorna o item atualizado'
          schema:
            $ref: "#/definitions/AtualizarItemResponse"
    
    delete:
      description: 'Remove um item registrado' 
      tags:
      - 'itens'
      parameters:
      - in: 'path'
        name: 'id'
        type: 'number'
        required: true
      responses:
        '204':
          description: 'Informa que removeu o item informado'
    
definitions:
  
  MensagensResponse:
    type: "object"
    properties:
      mensagensGlobais: 
        type: "array"
        items:
          type: "string"
      mensagensPorCampo:
        type: "array"
        items:
          type: "object"
          properties:
            campo:
              type: "string"
            erro:
              type: "string"
              
  NovoEventoRequest:
    type: "object"
    properties:
      nome: 
        type: "string"
      descricao: 
        type: "string"
        maximum: 400
      dataInicio:
        type: "string"
        format: "date"
      dataFim:
        type: "string"
        format: "date"
    required:
    - nome
    - dataInicio
        
  NovoEventoResponse:
    type: "object"
    properties:
      id:
        type: "number"
      nome: 
        type: "string"
      descricao: 
        type: "string"
      dataInicio:
        type: "string"
        format: "date"
      dataFim:
        type: "string"
        format: "date"
        
  EventoRegistrado:
    type: "object"
    properties:
      id:
        type: "number"
      nome: 
        type: "string"
      descricao: 
        type: "string"
      dataInicio:
        type: "string"
        format: "date"
      dataFim:
        type: "string"
        format: "date"
      
        
  AtualizarEventoRequest:
    type: "object"
    properties:
      nome: 
        type: "string"
      descricao: 
        type: "string"
      dataInicio:
        type: "string"
        format: "date"
      dataFim:
        type: "string"
        format: "date"
    required:
    - nome
    - dataInicio
    
  AtualizarEventoResponse:
    type: "object"
    properties:
      id:
        type: "number"
      nome: 
        type: "string"
      descricao: 
        type: "string"
      dataInicio:
        type: "string"
        format: "date"
      dataFim:
        type: "string"
        format: "date"
  
  ListaDeEventos:
    type: "array"
    items:
      $ref: '#/definitions/EventoRegistrado'  
      
  ItemEventoRegistrado:
    type: "object"
    properties:
      itemId: 
        type: number
      itemDescricao:
        type: string
  
  ListaItemEvento:
    type: "array"
    items:
      $ref: '#/definitions/ItemEventoRegistrado'
  
  RegistrarItemEventoRequest:
    type: "object"
    properties:
      itemId: 
        type: number
    required:
    - itemId
    
  RegistrarItemEventoResponse:
    type: "object"
    properties:
      itemId: 
        type: number
      itemDescricao:
        type: string
        
  NovoItemRequest:
    type: "object"
    properties:
      descricao: 
        type: "string"
      valorReferencia:
        type: number
        default: 0.00
    required:
    - descricao
    - valorReferencia
        
  NovoItemResponse:
    type: "object"
    properties:
      id:
        type: "number"
      descricao: 
        type: "string"
      valorReferencia:
        type: number
  
  ItemRegistrado:
    type: "object"
    properties:
      id:
        type: "number"
      descricao: 
        type: "string"
      valorReferencia:
        type: number
        
  AtualizarItemRequest:
    type: "object"
    properties:
      descricao: 
        type: "string"
      valorReferencia:
        type: number
    required:
    - descricao
    - valorReferencia
    
  AtualizarItemResponse:
    type: "object"
    properties:
      id:
        type: "number"
      descricao: 
        type: "string"
      valorReferencia:
        type: number
  
  ListaDeItens:
    type: "array"
    items:
      $ref: '#/definitions/ItemRegistrado'  
      
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"